### ISSUE TITLE
Can't compile on OS X 10.9

### ISSUE THREAD

**Issue by ehq** [pzorin/qgo#37]
Hey,

I installed QT and followed the steps in the README, but when I run `make` I get the following error:

``` bash
qgo (master) • make
cd src/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtMultimedia.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtMultimedia.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I. -Inetwork -Iaudio -Igtp -Igame_interfaces -Igame_tree -Iboard -Isgf -I../build/moc -I../build/ui -F/usr/local/Cellar/qt/4.8.6/lib -o ../build/objects/displayboard.o displayboard.cpp
displayboard.cpp:29:10: fatal error: 'QtWidgets' file not found
#include <QtWidgets>
         ^
1 error generated.
make[1]: *** [../build/objects/displayboard.o] Error 1
make: *** [sub-src-make_default] Error 2
```

Am I missing a required lib?
